In [54]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler


In [55]:
data=pd.read_csv("assignment3.csv")
data

experience   test score  interview score  salary
0          NaN         8.0                9     500
1          NaN         8.0                6     450
2          5.0         6.0                7     600
3          2.0        10.0               10     650
4          7.0         9.0                6     700
5          3.0         7.0               10     620
6         10.0         NaN                7     720
7         11.0         7.0                8     820

In [56]:
from sklearn.impute import SimpleImputer
impute=SimpleImputer(missing_values=np.nan,strategy='mean')

In [74]:
x=data.iloc[2:,1:4].values
y=data.iloc[2:,0].values

x

array([[  6.,   7., 600.],
       [ 10.,  10., 650.],
       [  9.,   6., 700.],
       [  7.,  10., 620.],
       [ nan,   7., 720.],
       [  7.,   8., 820.]])

In [86]:
impute.fit(x[:,0:3])
x[:,0:3]=impute.transform(x[:,0:3])
x

array([[  6. ,   7. , 600. ],
       [ 10. ,  10. , 650. ],
       [  9. ,   6. , 700. ],
       [  7. ,  10. , 620. ],
       [  7.8,   7. , 720. ],
       [  7. ,   8. , 820. ]])

splitting test and training set 

In [76]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
x_train=np.round(x_train,decimals=1)
x_train


array([[  7. ,   8. , 820. ],
       [  9. ,   6. , 700. ],
       [  7.8,   7. , 720. ],
       [  7. ,  10. , 620. ]])

In [87]:
regression=LinearRegression()
regression.fit(x_train,y_train)


LinearRegression()

In [88]:
y_pred = regression.predict(x_test)

In [101]:
y_pred = regression.predict([[8,9,500]])
y_pred

array([0.83333333])

In [102]:
y_pred = regression.predict([[8,6,450]])
y_pred

array([11.86111111])