In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [7]:
data=pd.read_csv("NFLX.csv")
data

Date        Open        High         Low       Close   Adj Close  \
0     2018-02-05  262.000000  267.899994  250.029999  254.259995  254.259995   
1     2018-02-06  247.699997  266.700012  245.000000  265.720001  265.720001   
2     2018-02-07  266.579987  272.450012  264.329987  264.559998  264.559998   
3     2018-02-08  267.079987  267.619995  250.000000  250.100006  250.100006   
4     2018-02-09  253.850006  255.800003  236.110001  249.470001  249.470001   
...          ...         ...         ...         ...         ...         ...   
1004  2022-01-31  401.970001  427.700012  398.200012  427.140015  427.140015   
1005  2022-02-01  432.959991  458.480011  425.540009  457.130005  457.130005   
1006  2022-02-02  448.250000  451.980011  426.480011  429.480011  429.480011   
1007  2022-02-03  421.440002  429.260010  404.279999  405.600006  405.600006   
1008  2022-02-04  407.309998  412.769989  396.640015  410.170013  410.170013   

        Volume  
0     11896100  
1     12595800  
2      8981500  
3      9306700  
4     16906900  
...        ...  
1004  20047500  
1005  22542300  
1006  14346000  
1007   9905200  
1008   7782400  

[1009 rows x 7 columns]

Replacing the 0 values in volume with Average value

In [8]:
#splitting the table
X=data.iloc[:,:-1].values
Y=data[["Volume"]].values
Y.shape
Y=np.array(Y)
Y


array([[11896100],
       [12595800],
       [ 8981500],
       ...,
       [14346000],
       [ 9905200],
       [ 7782400]], dtype=int64)

Replacing the null values with mean 

In [9]:
from sklearn.impute import SimpleImputer
impute=SimpleImputer(missing_values=0,strategy="mean")


In [10]:
impute.fit(Y)

SimpleImputer(missing_values=0)

Encoding the string values

In [18]:
from sklearn.preprocessing import LabelEncoder
encode=LabelEncoder()
X=encode.fit_transform(X[:,0]) 

In [19]:
X

array([   0,    1,    2, ..., 1006, 1007, 1008])

Splitting of Train and test Set 

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,random_state=1)
print(x_train)


[ 301  160  944  320  473  915  509  902  598  121  740  187   16  843
  486  463  349  957  479  106  481   23  839   69  430  452  552  676
  650  347  428  882   74  218  531  265  366  110  374  989  298  185
  286  589  794  953  523   61  355  335  443  677  647  812  745  613
  307  853  134   33  772  354   57  781  810  800  894  525  318  291
   46  277  860  935  224  537  280  608    0  453  764  507   66  415
  439  414  578  554  294  364 1003  245  257  161  730  612  678  869
  863  649  247  872  239  220  837   92  114  543  988   76  990  474
  969  132  528  372   58  289  246  551  880   40   89  192  434   68
  711  436  382  139  541  482  118  429  931  799  350  736  446  496
  385  940  641   14  375   82  807  704  782  521   88  363  273  587
  172  947  103  762  491  371   45  432  457  928  761  892   11  214
  344  920  727  147  299  283  975  412  636  803  994  697  743  173
  927  868  226  305   31  921  841  602  285  483  494  922  623  116
  661 

In [21]:
print(x_test)


[ 986  923  293  555  582  248  718  673  329   49  708  142  948  250
  535  133  104    6  422  679  976  484  433   27  389  119  108  765
  832  833  919  725  867  546  274  200   78  680  262  937  563  156
   90  101   94  808  576   41  517  865  435   34  175   35  148  467
  652  684  980  692  311  699  464  742  663  726  956  824  992   17
  207  340  244  604  241   65  593  314  449  191  929  750  911  223
  186  180  268  709  977  345  664  936  895  472  759  874  702  802
  559  154  579   13  408  480  683  426  688  530  658  870  934  306
  267   59  877  386  189  791  120  368  938  768    3  195  205  331
  703  459  733  721  592  309  639    2  878 1005  779  999  713  961
   73  117  388  493  111    5  403  926  757  419  840 1001    8  358
   56  258  897  495  698   84  625  159  716  125  966  962  851  383
  370  805  950  339   81  238  455  577  202  959  228  991  216  758
   50  516  945  538  600  201  844  194  395  672  834  236  756  255
  590 

In [22]:
print(y_train)

[[18054100]
 [ 9322500]
 [ 2334900]
 [ 6340100]
 [ 9914900]
 [ 2526200]
 [ 4485400]
 [ 2681200]
 [ 6272100]
 [18260700]
 [ 5032100]
 [20360300]
 [ 7653500]
 [ 3124000]
 [ 4718300]
 [ 4457800]
 [ 3669700]
 [ 2764400]
 [ 3713300]
 [11127500]
 [ 3806900]
 [14500200]
 [ 2791900]
 [ 4746100]
 [12599200]
 [ 5111800]
 [16128700]
 [ 5391100]
 [ 9071100]
 [ 4830200]
 [38258900]
 [ 1919400]
 [ 5964400]
 [ 9634700]
 [10013900]
 [ 4944600]
 [17718000]
 [15719000]
 [ 6563200]
 [ 3381700]
 [15646200]
 [21698800]
 [ 7852400]
 [ 6797000]
 [ 3938600]
 [ 2077400]
 [ 8747000]
 [ 6135800]
 [ 3732200]
 [ 3710000]
 [ 5928500]
 [ 5602500]
 [ 4941400]
 [ 3193000]
 [11802100]
 [15083300]
 [ 5621900]
 [ 5299100]
 [ 6689700]
 [ 9529900]
 [ 3042200]
 [ 3799000]
 [ 7074400]
 [ 3484300]
 [ 4388800]
 [ 2944100]
 [ 2109500]
 [ 7405500]
 [ 8026700]
 [ 5368900]
 [10249400]
 [ 5271400]
 [ 2722500]
 [ 8437100]
 [14402700]
 [ 8767200]
 [ 7541400]
 [ 5669900]
 [11896100]
 [ 7488400]
 [ 2456200]
 [ 4772900]
 [ 5302300]
 [ 6

In [23]:
print(y_test)

[[ 4393100]
 [ 9534300]
 [ 3905500]
 [23177600]
 [ 5254900]
 [ 8535500]
 [ 3018200]
 [ 7988700]
 [ 5658900]
 [33866500]
 [ 3598600]
 [ 9222600]
 [ 2415600]
 [ 9051400]
 [13449400]
 [11784500]
 [ 8448900]
 [ 6855200]
 [ 6794400]
 [ 5113100]
 [ 3358400]
 [ 7104500]
 [ 4827400]
 [ 5642900]
 [ 4974200]
 [ 6993700]
 [ 9713900]
 [ 2841500]
 [ 2465300]
 [ 3253800]
 [ 6221000]
 [ 3894000]
 [ 3442100]
 [ 7046400]
 [ 5387300]
 [12993800]
 [ 9717900]
 [ 6347400]
 [ 6227900]
 [ 3833500]
 [ 8299900]
 [10414000]
 [14598300]
 [ 9252500]
 [16494600]
 [ 9061100]
 [ 5607300]
 [10655200]
 [ 8934100]
 [ 4659500]
 [ 6248400]
 [11988300]
 [11215000]
 [12068600]
 [13050200]
 [ 4766600]
 [ 5572700]
 [ 6997900]
 [ 2061500]
 [ 3690200]
 [ 5398200]
 [ 5063700]
 [ 5748400]
 [ 5895800]
 [ 3726400]
 [ 1906600]
 [ 2613700]
 [ 2882500]
 [ 3787400]
 [11932100]
 [15431500]
 [ 6209300]
 [11152900]
 [ 4198500]
 [17941400]
 [ 5633400]
 [ 4467900]
 [ 6974900]
 [ 6333800]
 [ 9710400]
 [ 2420300]
 [ 5969000]
 [ 4145100]
 [ 9

Feature Scaling not neccessarily need to be done for data sets